GO

DROP TABLE IF EXISTS Game
DROP TABLE IF EXISTS Player
DROP DATABASE IF EXISTS DB_Football_Games

GO

CREATE DATABASE DB_Football_Games

GO

USE DB_Football_Games

GO

CREATE TABLE Player
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Wins INT NOT NULL DEFAULT 0,
	Ties INT NOT NULL DEFAULT 0,
	Loses INT NOT NULL DEFAULT 0,
	GoalsScored INT NOT NULL DEFAULT 0,
	GoalsConceded INT NOT NULL DEFAULT 0,
);

CREATE TABLE Game
(
	Id INT PRIMARY KEY IDENTITY (1,1),
	HomePlayerId INT NOT NULL,
	AwayPlayerId INT NOT NULL,
	GameDate DATE NOT NULL DEFAULT GETDATE(),
	HomePlayerGoals INT NOT NULL,
	AwayPlayerGoals INT NOT NULL,
	FOREIGN KEY (HomePlayerId) REFERENCES Player(Id),
	FOREIGN KEY (AwayPlayerId) REFERENCES Player(Id)
);